const DAY=864e5,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?.()||("id-"+Date.now()+"-"+Math.random().toString(36).slice(2));
const esc=value=>String(value??"").replace(/[&<>'"]/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[ch]));
const DEMO=[
{id:"1",name:"Mary",pet:"Bella",phone:"(305) 555-0101",zip:"33178",last:"2026-07-20",next:"",frequency:42,value:135,wait:true,notes:"Flexible afternoons"},
{id:"2",name:"John",pet:"Max",phone:"(305) 555-0102",zip:"33178",last:"2026-07-28",next:"2026-09-18",frequency:42,value:120,wait:false,notes:"Prefers text"},
{id:"3",name:"Lisa",pet:"Luna",phone:"(305) 555-0103",zip:"33172",last:"2026-07-10",next:"",frequency:56,value:110,wait:true,notes:"Asked for an earlier opening"},
{id:"4",name:"Emma",pet:"Charlie",phone:"(305) 555-0104",zip:"33178",last:"2026-06-30",next:"",frequency:42,value:145,wait:false,notes:"Large dog; allow 2 hours"},
{id:"5",name:"David",pet:"Cooper",phone:"(305) 555-0105",zip:"33172",last:"2026-08-15",next:"2026-09-17",frequency:42,value:130,wait:true,notes:"Can move appointments"},
{id:"6",name:"Sofia",pet:"Milo",phone:"(305) 555-0106",zip:"33186",last:"2026-08-30",next:"2026-10-20",frequency:56,value:95,wait:false,notes:"Mornings only"},
{id:"7",name:"Alex",pet:"Daisy",phone:"(305) 555-0107",zip:"33178",last:"2026-08-07",next:"",frequency:28,value:140,wait:false,notes:"Available after 1 PM"},
{id:"8",name:"Nina",pet:"Rocky",phone:"(305) 555-0108",zip:"33172",last:"2026-07-22",next:"",frequency:42,value:150,wait:false,notes:"Call before texting"}];
let clients=JSON.parse(localStorage.getItem("gg_clients")||"null")||structuredClone(DEMO),attempts=JSON.parse(localStorage.getItem("gg_attempts")||"[]"),slot=null;
const save=()=>{localStorage.gg_clients=JSON.stringify(clients);localStorage.gg_attempts=JSON.stringify(attempts)};
const date=s=>s?new Date(s+"T12:00:00"):null;
const fmtDate=s=>date(s)?.toLocaleDateString("en-US",{weekday:"short",month:"short",day:"numeric"})||"—";
const money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n||0);
function toast(t){$("#toast").textContent=t;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),1600)}
function view(id){$$(".view").forEach(x=>x.classList.toggle("active",x.id===id));$$("nav [data-view]").forEach(x=>{let active=x.dataset.view===id;x.classList.toggle("active",active);x.setAttribute("aria-current",active?"page":"false")});if(id==="clients")renderClients();if(id==="dashboard")renderDashboard();scrollTo({top:0,behavior:"smooth"})}
$$("[data-view]").forEach(x=>x.onclick=e=>{e.preventDefault();view(x.dataset.view)});
function score(c){
 let n=0,r=[],open=date(slot.date),last=date(c.last),next=date(c.next),due=last&&c.frequency?new Date(last.getTime()+c.frequency*DAY):null;
 if(c.zip===slot.zip){n+=30;r.push("Same ZIP")}
 if(c.wait){n+=25;r.push("On waitlist")}
 if(due&&open>=due){n+=25;r.push("Overdue for grooming")}
 if(!next){n+=15;r.push("No future appointment")}else{let d=Math.round((next-open)/DAY);if(d>=0&&d<=21){n+=10;r.push("Future appointment could move up")}}
 if(slot.value&&c.value&&Math.abs(c.value-slot.value)/slot.value<=.25){n+=5;r.push("Similar appointment value")}
 if(/flexible|opening|available|move/i.test(c.notes)){n+=5;r.push("Flexible based on notes")}
 return {...c,score:Math.min(100,n),reasons:r}
}
function message(c){let d=date(slot.date).toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"}),t=new Date("2000-01-01T"+slot.time).toLocaleTimeString("en-US",{hour:"numeric",minute:"2-digit"});return `Hi ${c.name}! We had an opening become available in your area on ${d} at ${t}. Would you like me to reserve it for ${c.pet}?`}
$("#slotForm").onsubmit=e=>{e.preventDefault();slot={date:$("#sDate").value,time:$("#sTime").value,zip:$("#sZip").value,value:+$("#sValue").value||0,duration:$("#sDuration").value};renderMatches()};
function renderMatches(){
 let ranked=clients.map(score).filter(x=>x.score>=20).sort((a,b)=>b.score-a.score||a.pet.localeCompare(b.pet));
 $(".slot").classList.add("hidden");$("#results").classList.toggle("hidden",!ranked.length);$("#noMatches").classList.toggle("hidden",!!ranked.length);$(".steps").innerHTML="<span>✓ Opening</span><i></i><b>2 Matches</b><i></i><span>3 Outcome</span>";
 $("#summary").textContent=`${fmtDate(slot.date)} · ${slot.time} · ZIP ${slot.zip}${slot.value?" · "+money(slot.value):""}`;
 $("#candidates").innerHTML=ranked.map((c,i)=>`<article class="candidate ${i?"":"best"}" data-id="${esc(c.id)}"><div class="candidateTop"><div><h3>${esc(c.pet)}<span class="badge">${i?"MATCH":"BEST MATCH"}</span></h3><p>${esc(c.name)} · ${esc(c.phone)} · ZIP ${esc(c.zip)}</p></div><div class="score" aria-label="Match score ${c.score} out of 100"><b>${c.score}</b><small>/ 100</small></div></div><div class="reasons">${c.reasons.map(x=>`<span class="reason">${esc(x)}</span>`).join("")}</div><div class="message">${esc(message(c))}</div><div class="candidateActions"><button class="secondary copy">Copy Message</button><button class="outcome" data-o="Declined">Declined</button><button class="outcome" data-o="No Reply">No Reply</button><button class="outcome filled" data-o="Filled">Mark Filled</button></div></article>`).join("");
 $$(".copy").forEach(b=>b.onclick=async()=>{let c=clients.find(x=>x.id===b.closest(".candidate").dataset.id);try{await navigator.clipboard.writeText(message(c));toast("Message copied")}catch{toast("Select and copy the message manually")}});
 $$("[data-o]").forEach(b=>b.onclick=()=>outcome(b.closest(".candidate").dataset.id,b.dataset.o));scrollTo({top:$("#results").offsetTop-75,behavior:"smooth"})
}
function outcome(id,result){let c=clients.find(x=>x.id===id);attempts.unshift({id:uid(),created:new Date().toISOString(),slot:{...slot},client:c.name,pet:c.pet,outcome:result,recovered:result==="Filled"?(slot.value||c.value):0});save();toast(result==="Filled"?"Opening marked as filled":"Outcome saved: "+result);if(result==="Filled"){setTimeout(()=>view("dashboard"),500)}}
function resetForm(){$("#slotForm").reset();let today=new Date(),d=new Date(today.getFullYear(),today.getMonth(),today.getDate()+1),iso=d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0");$("#sDate").min=today.toLocaleDateString("en-CA");$("#sDate").value=iso;$("#sTime").value="14:00"}
$("#clearSlot").onclick=resetForm;$("#editSlot").onclick=()=>{$("#results").classList.add("hidden");$("#noMatches").classList.add("hidden");$(".slot").classList.remove("hidden");$(".steps").innerHTML="<b>1 Opening</b><i></i><span>2 Matches</span><i></i><span>3 Outcome</span>"};
function renderClients(q=""){q=q.toLowerCase();let rows=clients.filter(c=>[c.name,c.pet,c.phone,c.zip].some(v=>String(v).toLowerCase().includes(q)));$("#clientList").innerHTML=rows.length?`<div class="tableWrap"><table><thead><tr><th>CLIENT / PET</th><th>PHONE</th><th>ZIP</th><th>LAST GROOM</th><th>NEXT APPT.</th><th>WAITLIST</th><th>AVG. VALUE</th><th></th></tr></thead><tbody>${rows.map(c=>`<tr><td><b>${esc(c.pet)}</b><br><small>${esc(c.name)}</small></td><td>${esc(c.phone)}</td><td>${esc(c.zip)}</td><td>${fmtDate(c.last)}</td><td>${fmtDate(c.next)}</td><td>${c.wait?"Yes":"No"}</td><td>${money(c.value)}</td><td><button class="edit" data-edit="${esc(c.id)}" aria-label="Edit ${esc(c.name)} and ${esc(c.pet)}">Edit</button></td></tr>`).join("")}</tbody></table></div>`:`<article class="card empty"><div>🐾</div><h2>No clients yet</h2><p>Add your first client or reload fictitious demo data.</p><button class="primary" id="firstClient">Add first client</button></article>`;$$("[data-edit]").forEach(b=>b.onclick=()=>openClient(b.dataset.edit));$("#firstClient")?.addEventListener("click",()=>openClient())}
function openClient(id){$("#clientForm").reset();$("#cId").value=id||"";$("#modalTitle").textContent=id?"Edit client":"Add client";if(id){let c=clients.find(x=>x.id===id);["Name","Pet","Phone","Zip","Last","Next","Frequency","Value","Notes"].forEach(k=>$("#c"+k).value=c[k.toLowerCase()]??"");$("#cWait").checked=c.wait}$("#clientModal").showModal()}
$("#addClient").onclick=()=>openClient();$("#search").oninput=e=>renderClients(e.target.value);$("#demo").onclick=()=>{clients=structuredClone(DEMO);save();renderClients();toast("Demo clients loaded")};$("#fresh").onclick=()=>{if(confirm("Remove all clients and recovery history from this device?")){clients=[];attempts=[];save();renderClients();toast("Local data cleared")}};
$("#saveClient").onclick=e=>{if(!$("#clientForm").reportValidity()){e.preventDefault();return}let id=$("#cId").value||uid(),c={id,name:$("#cName").value.trim(),pet:$("#cPet").value.trim(),phone:$("#cPhone").value.trim(),zip:$("#cZip").value,last:$("#cLast").value,next:$("#cNext").value,frequency:+$("#cFrequency").value||null,value:+$("#cValue").value||0,wait:$("#cWait").checked,notes:$("#cNotes").value.trim()},i=clients.findIndex(x=>x.id===id);i<0?clients.push(c):clients[i]=c;save();setTimeout(()=>{renderClients();toast("Client saved")})};
function renderDashboard(){let key=a=>a.slot.date+"|"+a.slot.time+"|"+a.slot.zip,slotKeys=new Set(attempts.map(key)),filledBySlot=new Map();attempts.filter(a=>a.outcome==="Filled").forEach(a=>{if(!filledBySlot.has(key(a)))filledBySlot.set(key(a),a)});let slots=slotKeys.size,filled=[...filledBySlot.values()],rate=slots?Math.round(filled.length/slots*100):0,revenue=filled.reduce((s,a)=>s+a.recovered,0);$("#metrics").innerHTML=[["Cancelled appointments",slots],["Filled openings",filled.length],["Fill rate",rate+"%"],["Recovered revenue",money(revenue)]].map(x=>`<div class="metric"><span>${x[0]}</span><b>${x[1]}</b></div>`).join("");$("#history").innerHTML=attempts.length?attempts.slice(0,10).map(a=>`<div class="row"><p><b>${esc(a.pet)}</b> · ${esc(a.client)}<br><small>${fmtDate(a.slot.date)} at ${esc(a.slot.time)} · ZIP ${esc(a.slot.zip)}</small></p><span class="status ${esc(a.outcome.replace(" ",""))}">${esc(a.outcome)}</span></div>`).join(""):"<p class='note'>No attempts recorded yet.</p>";let z={};attempts.forEach(a=>z[a.slot.zip]=(z[a.slot.zip]||0)+1);$("#zips").innerHTML=Object.keys(z).length?Object.entries(z).sort((a,b)=>b[1]-a[1]).map(([k,n])=>`<div class="row"><p><b>${esc(k)}</b><br><small>${n} attempt${n>1?"s":""}</small></p><span>${Math.round(n/attempts.length*100)}%</span></div>`).join(""):"<p class='note'>ZIP insights appear after your first attempt.</p>"}
resetForm();renderClients();renderDashboard();view("recover");
